apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: crypto
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: django-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: django-app
    spec:
      containers:
        - name: django-container
          image: registry-c7e79e924d-nd.apps.ir-central1.arvancaas.ir/crypto:1.0.54
          imagePullPolicy: Always
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: DATABASE_NAME
                  name: mysql-credentials
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: DATABASE_USER
                  name: mysql-credentials
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DATABASE_PASSWORD
                  name: mysql-credentials
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_HOST
                  name: django-config
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: django-config
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: my-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30