apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS1jN2U3OWU5MjRkLW5kLmFwcHMuaXItY2VudHJhbDEuYXJ2YW5jYWFzLmlyIjp7InVzZXJuYW1lIjoicXVyYW5hcGkiLCJwYXNzd29yZCI6Inp4Y3Zibm1uYmdoamhoamtqaGdoamtqaGdmZGZnaGpramhnY2ZnYm4iLCJhdXRoIjoiY1hWeVlXNWhjR2s2ZW5oamRtSnViVzVpWjJocWFHaHFhMnBvWjJocWEycG9aMlprWm1kb2FtdHFhR2RqWm1kaWJnPT0ifX19
kind: Secret
metadata:
  name: my-registry-secret
  namespace: crypto
type: kubernetes.io/dockerconfigjson